// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repository

import (
	"context"
	"github.com/kageyamountain/kageyamountain.net-backend/internal/domain/model/entity"
	"github.com/kageyamountain/kageyamountain.net-backend/internal/domain/model/value"
	"sync"
)

// Ensure, that ArticleRepositoryMock does implement ArticleRepository.
// If this is not the case, regenerate this file with moq.
var _ ArticleRepository = &ArticleRepositoryMock{}

// ArticleRepositoryMock is a mock implementation of ArticleRepository.
//
//	func TestSomethingThatUsesArticleRepository(t *testing.T) {
//
//		// make and configure a mocked ArticleRepository
//		mockedArticleRepository := &ArticleRepositoryMock{
//			FindAllForListFunc: func(ctx context.Context) ([]*entity.Article, error) {
//				panic("mock out the FindAllForList method")
//			},
//			FindByIDFunc: func(ctx context.Context, articleID *value.ArticleID) (*entity.Article, error) {
//				panic("mock out the FindByID method")
//			},
//		}
//
//		// use mockedArticleRepository in code that requires ArticleRepository
//		// and then make assertions.
//
//	}
type ArticleRepositoryMock struct {
	// FindAllForListFunc mocks the FindAllForList method.
	FindAllForListFunc func(ctx context.Context) ([]*entity.Article, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, articleID *value.ArticleID) (*entity.Article, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindAllForList holds details about calls to the FindAllForList method.
		FindAllForList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ArticleID is the articleID argument value.
			ArticleID *value.ArticleID
		}
	}
	lockFindAllForList sync.RWMutex
	lockFindByID       sync.RWMutex
}

// FindAllForList calls FindAllForListFunc.
func (mock *ArticleRepositoryMock) FindAllForList(ctx context.Context) ([]*entity.Article, error) {
	if mock.FindAllForListFunc == nil {
		panic("ArticleRepositoryMock.FindAllForListFunc: method is nil but ArticleRepository.FindAllForList was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockFindAllForList.Lock()
	mock.calls.FindAllForList = append(mock.calls.FindAllForList, callInfo)
	mock.lockFindAllForList.Unlock()
	return mock.FindAllForListFunc(ctx)
}

// FindAllForListCalls gets all the calls that were made to FindAllForList.
// Check the length with:
//
//	len(mockedArticleRepository.FindAllForListCalls())
func (mock *ArticleRepositoryMock) FindAllForListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockFindAllForList.RLock()
	calls = mock.calls.FindAllForList
	mock.lockFindAllForList.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *ArticleRepositoryMock) FindByID(ctx context.Context, articleID *value.ArticleID) (*entity.Article, error) {
	if mock.FindByIDFunc == nil {
		panic("ArticleRepositoryMock.FindByIDFunc: method is nil but ArticleRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ArticleID *value.ArticleID
	}{
		Ctx:       ctx,
		ArticleID: articleID,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, articleID)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedArticleRepository.FindByIDCalls())
func (mock *ArticleRepositoryMock) FindByIDCalls() []struct {
	Ctx       context.Context
	ArticleID *value.ArticleID
} {
	var calls []struct {
		Ctx       context.Context
		ArticleID *value.ArticleID
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}
