version: 2
updates:
  # Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule: # 毎月第一金曜日の20時
      interval: "monthly"
      day: "friday"
      time: "20:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    reviewers:
      - "kageyamountain"
    assignees:
      - "kageyamountain"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule: # 毎月第一金曜日の20時
      interval: "monthly"
      day: "friday"
      time: "20:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    reviewers:
      - "kageyamountain"
    assignees:
      - "kageyamountain"
