version: 2
updates:
  # Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    groups:
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
          - "github.com/aws/smithy-go"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
    assignees:
      - "kageyamountain"
    labels:
      - "dependencies"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    assignees:
      - "kageyamountain"
    labels:
      - "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    assignees:
      - "kageyamountain"
    labels:
      - "dependencies"
