FROM golang:1.25.1-alpine3.22 AS dev
RUN apk add --no-cache \
    tzdata \
    curl \
    gcc \
    musl-dev \
    git
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | \
    sh -s -- -b $(go env GOPATH)/bin v2.5.0
RUN go install github.com/air-verse/air@latest && \
    go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
CMD ["air"]
