FROM golang:1.26.3-alpine AS dev
RUN apk add --no-cache \
    tzdata \
    curl \
    gcc \
    musl-dev \
    git
RUN curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.12.2
RUN go install github.com/air-verse/air@latest && \
    go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
CMD ["air"]
