// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package articles_get

import (
	"context"
	"sync"
)

// Ensure, that UseCaseMock does implement UseCase.
// If this is not the case, regenerate this file with moq.
var _ UseCase = &UseCaseMock{}

// UseCaseMock is a mock implementation of UseCase.
//
//	func TestSomethingThatUsesUseCase(t *testing.T) {
//
//		// make and configure a mocked UseCase
//		mockedUseCase := &UseCaseMock{
//			ExecuteFunc: func(ctx context.Context) (*UseCaseOutput, error) {
//				panic("mock out the Execute method")
//			},
//		}
//
//		// use mockedUseCase in code that requires UseCase
//		// and then make assertions.
//
//	}
type UseCaseMock struct {
	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(ctx context.Context) (*UseCaseOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockExecute sync.RWMutex
}

// Execute calls ExecuteFunc.
func (mock *UseCaseMock) Execute(ctx context.Context) (*UseCaseOutput, error) {
	if mock.ExecuteFunc == nil {
		panic("UseCaseMock.ExecuteFunc: method is nil but UseCase.Execute was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(ctx)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//
//	len(mockedUseCase.ExecuteCalls())
func (mock *UseCaseMock) ExecuteCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}
