// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 記事一覧情報取得API
	// (GET /articles)
	ArticlesGet(c *gin.Context, params ArticlesGetParams)
	// 記事情報取得API
	// (GET /articles/{article-id})
	ArticleGet(c *gin.Context, articleId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ArticlesGet operation middleware
func (siw *ServerInterfaceWrapper) ArticlesGet(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ArticlesGetParams

	// ------------- Optional query parameter "publish-year" -------------

	err = runtime.BindQueryParameter("form", true, false, "publish-year", c.Request.URL.Query(), &params.PublishYear)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter publish-year: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameter("form", true, false, "tags", c.Request.URL.Query(), &params.Tags)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tags: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ArticlesGet(c, params)
}

// ArticleGet operation middleware
func (siw *ServerInterfaceWrapper) ArticleGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "article-id" -------------
	var articleId string

	err = runtime.BindStyledParameterWithOptions("simple", "article-id", c.Param("article-id"), &articleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter article-id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ArticleGet(c, articleId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/articles", wrapper.ArticlesGet)
	router.GET(options.BaseURL+"/articles/:article-id", wrapper.ArticleGet)
}
