// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package v1

import (
	"time"
)

// Defines values for ErrorCode.
const (
	InternalServerError ErrorCode = "internal_server_error"
	NotFound            ErrorCode = "not_found"
)

// ArticleContents 記事内容（マークダウン形式）
type ArticleContents = string

// ArticleDetail defines model for ArticleDetail.
type ArticleDetail struct {
	// Contents 記事内容（マークダウン形式）
	Contents ArticleContents `json:"contents"`

	// Id 記事ID（ハイフン無しのUUIDv4形式）
	Id ArticleId `json:"id"`

	// PublishedAt 公開日時（UTC）
	PublishedAt ArticlePublishedAt `json:"published_at"`

	// Tags タグ
	Tags ArticleTags `json:"tags"`

	// Title 記事タイトル
	Title ArticleTitle `json:"title"`

	// UpdatedAt 更新日時（UTC）
	UpdatedAt ArticleUpdatedAt `json:"updated_at"`
}

// ArticleGetResponseBody defines model for ArticleGetResponseBody.
type ArticleGetResponseBody struct {
	Article ArticleDetail `json:"article"`
}

// ArticleId 記事ID（ハイフン無しのUUIDv4形式）
type ArticleId = string

// ArticlePublishedAt 公開日時（UTC）
type ArticlePublishedAt = time.Time

// ArticleSummary defines model for ArticleSummary.
type ArticleSummary struct {
	// Id 記事ID（ハイフン無しのUUIDv4形式）
	Id ArticleId `json:"id"`

	// PublishedAt 公開日時（UTC）
	PublishedAt ArticlePublishedAt `json:"published_at"`

	// Tags タグ
	Tags ArticleTags `json:"tags"`

	// Title 記事タイトル
	Title ArticleTitle `json:"title"`
}

// ArticleTags タグ
type ArticleTags = []string

// ArticleTitle 記事タイトル
type ArticleTitle = string

// ArticleUpdatedAt 更新日時（UTC）
type ArticleUpdatedAt = time.Time

// ArticlesGetResponseBody defines model for ArticlesGetResponseBody.
type ArticlesGetResponseBody struct {
	Articles []ArticleSummary `json:"articles"`
}

// Error defines model for Error.
type Error struct {
	// Code エラーコード
	Code ErrorCode `json:"code"`

	// Details エラーの詳細情報
	Details *map[string]string `json:"details,omitempty"`

	// Message エラーメッセージ
	Message string `json:"message"`
}

// ErrorCode エラーコード
type ErrorCode string

// RequestID リクエストID（UUIDv4形式）
type RequestID = string

// ArticlesGetParams defines parameters for ArticlesGet.
type ArticlesGetParams struct {
	// PublishYear 公開年でフィルタリング
	PublishYear *int `form:"publish-year,omitempty" json:"publish-year,omitempty"`

	// Tags タグでフィルタリング（複数指定可能）
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`
}
